<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @php
        $website_info = \App\Models\Setting::where('key', 'website_common_info')->first();
        if ($website_info && $website_info->value) {
            $website_info = json_decode($website_info->value, true);
        }
    @endphp
    <title>New Contact Form Submission from {{ $website_info['web_name'] ?? '' }} </title>
</head>

<body>
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:30px 15px;">
        <tr>
            <td align="center">
                <table width="650" cellpadding="0" cellspacing="0"
                    style="max-width:650px;background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e7eb;">
                    <!-- Header -->
                    <tr>
                        <td
                            style="background:#0d6efd;padding:25px;text-align:center;color:#ffffff;font-size:24px;font-weight:bold;">
                            New Contact Form Submission </td>
                    </tr> <!-- Content -->
                    <tr>
                        <td style="padding:30px;">
                            <p style="margin:0 0 15px;font-size:16px;"> Dear <strong>Admin</strong>, </p>
                            <p style="margin:0 0 20px;font-size:15px;line-height:1.6;"> A new contact form has been
                                submitted through <strong>{{ $website_info['web_name'] ?? 'Website' }}</strong>. The
                                submission details are provided below: </p>
                            <table width="100%" cellpadding="0" cellspacing="0"
                                style="border-collapse:collapse;border:1px solid #e5e7eb;">
                                <tr>
                                    <td
                                        style="padding:12px;background:#f8fafc;border-bottom:1px solid #e5e7eb;font-weight:bold;width:180px;">
                                        Name </td>
                                    <td style="padding:12px;border-bottom:1px solid #e5e7eb;">
                                        {{ $data['name'] ?? '-' }} </td>
                                </tr>
                                <tr>
                                    <td
                                        style="padding:12px;background:#f8fafc;border-bottom:1px solid #e5e7eb;font-weight:bold;">
                                        Email </td>
                                    <td style="padding:12px;border-bottom:1px solid #e5e7eb;">
                                        {{ $data['email'] ?? '-' }} </td>
                                </tr>
                                <tr>
                                    <td
                                        style="padding:12px;background:#f8fafc;border-bottom:1px solid #e5e7eb;font-weight:bold;">
                                        Phone </td>
                                    <td style="padding:12px;border-bottom:1px solid #e5e7eb;">
                                        {{ $data['phone'] ?? '-' }} </td>
                                </tr>
                                <tr>
                                    <td
                                        style="padding:12px;background:#f8fafc;border-bottom:1px solid #e5e7eb;font-weight:bold;">
                                        Subject </td>
                                    <td style="padding:12px;border-bottom:1px solid #e5e7eb;">
                                        {{ $data['subject'] ?? '-' }} </td>
                                </tr>
                                <tr>
                                    <td style="padding:12px;background:#f8fafc;font-weight:bold;vertical-align:top;">
                                        Message </td>
                                    <td style="padding:12px;line-height:1.7;"> {!! nl2br(e($data['message'] ?? '-')) !!} </td>
                                </tr>
                            </table>
                            <p style="margin:25px 0 0;font-size:15px;line-height:1.6;"> Please review and respond to
                                this inquiry at your earliest convenience. </p>
                        </td>
                    </tr> <!-- Footer -->
                    <tr>
                        <td
                            style="background:#f8fafc;padding:20px;text-align:center;font-size:13px;color:#6b7280;border-top:1px solid #e5e7eb;">
                            This email was automatically generated by
                            <strong>{{ $website_info['web_name'] ?? 'Website' }}</strong>.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>
